/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AddressId } from './addressId.ts';

export interface Address {
  address: string;
  city: string;
  country: string;
  created_at: string;
  id: AddressId;
  postal_code: string;
  state: string;
}
