/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CartId } from './cartId.ts';
import type { CartItem } from './cartItem.ts';

export interface AddToCartResponse {
  cart_id: CartId;
  item: CartItem;
}
