/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PromotionId } from './promotionId.ts';
import type { UserId } from './userId.ts';

export type AdjustmentSource = {
  Promotion: {
  code: string;
  promotion_id: PromotionId;
};
} | {
  Manual: {
  created_by: UserId;
};
};
