/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type Allocation = typeof Allocation[keyof typeof Allocation];


export const Allocation = {
  across: 'across',
  each: 'each',
} as const;
