/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Allocation } from './allocation.ts';
import type { ApplicationMethodId } from './applicationMethodId.ts';
import type { ApplicationTarget } from './applicationTarget.ts';
import type { DiscountValue } from './discountValue.ts';
import type { PromotionRule } from './promotionRule.ts';

export type ApplicationMethod = {
  Standard: {
  allocation?: null | Allocation;
  id: ApplicationMethodId;
  /** @nullable */
  max_quantity?: number | null;
  target: ApplicationTarget;
  target_rules: PromotionRule[];
  value: DiscountValue;
};
} | {
  BuyGet: {
  apply_to_quantity: number;
  buy_rules: PromotionRule[];
  buy_rules_min_quantity: number;
  id: ApplicationMethodId;
  target_rules: PromotionRule[];
  value: DiscountValue;
};
};
