/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type ApplicationTarget = typeof ApplicationTarget[keyof typeof ApplicationTarget];


export const ApplicationTarget = {
  items: 'items',
  order: 'order',
} as const;
