/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type AssignmentMode = typeof AssignmentMode[keyof typeof AssignmentMode];


export const AssignmentMode = {
  add: 'add',
  replace: 'replace',
} as const;
