/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role.ts';
import type { UserId } from './userId.ts';

export interface AssignRolesToUserResponse {
  roles: Role[];
  user_id: UserId;
}
