/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AssignmentMode } from './assignmentMode.ts';
import type { RoleId } from './roleId.ts';

export interface AssignRolesToUserRequest {
  mode?: null | AssignmentMode;
  role_ids: RoleId[];
}
