/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AddressSnapshot } from './addressSnapshot.ts';

/**
 * `{from, to}` aggregate value used for address snapshots on
 * `sales_order.updated` audit events (e.g. `billing_address`,
 * `shipping_address`).
 */
export interface AuditFromToAddress {
  from: AddressSnapshot;
  to: AddressSnapshot;
}
