/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentTermId } from './paymentTermId.ts';

/**
 * `{from, to}` aggregate value used for the payment term identifier on
 * `sales_order.updated` audit events.
 */
export interface AuditFromToPaymentTermId {
  from?: null | PaymentTermId;
  to?: null | PaymentTermId;
}
