/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

/**
 * `{from, to}` aggregate value used for scalar fields on `sales_order.updated`
 * audit events (e.g. `grand_total`, `line_count`).
 */
export interface AuditFromToI64 {
  from: number;
  to: number;
}
