/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AuditActorResponse } from './auditActorResponse.ts';
import type { AuditEntityReferenceResponse } from './auditEntityReferenceResponse.ts';
import type { AuditLogId } from './auditLogId.ts';

/**
 * API representation of an audit event.
 *
 * `metadata` is intended for non-sensitive source information (e.g. request
 * ids). IP addresses or authentication data must never be stored here.
 */
export interface AuditEventResponse {
  action: string;
  actor?: null | AuditActorResponse;
  data: unknown;
  entity: AuditEntityReferenceResponse;
  id: AuditLogId;
  metadata: unknown;
  occurred_at: string;
}
