/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId.ts';

/**
 * Resolved actor information for an audit event.
 */
export interface AuditActorResponse {
  email: string;
  id: UserId;
  name: string;
}
