/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

/**
 * API representation of the audited entity. Serialized literals are stable
 * because they come from the domain enums' Display implementations.
 */
export interface AuditEntityReferenceResponse {
  entity_id: string;
  entity_type: string;
}
