/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';

export interface BrandSalesKpi {
  brand_id: BrandId;
  name: string;
  order_count: number;
  sales_total: number;
  units_sold: number;
}
