/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface CancellationCounts {
  from_confirmed: number;
  from_draft: number;
  from_quote: number;
  total: number;
}
