/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CartItemId } from './cartItemId.ts';
import type { VariantId } from './variantId.ts';
import type { VariantImage } from './variantImage.ts';
import type { VariantPrice } from './variantPrice.ts';
import type { VariantProperty } from './variantProperty.ts';

export interface CartItemResponse {
  currency: string;
  display_name: string;
  id: CartItemId;
  images: VariantImage[];
  line_total: number;
  prices: VariantPrice[];
  properties: VariantProperty[];
  quantity: number;
  sku: string;
  unit_price: number;
  variant_id: VariantId;
}
