/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CartId } from './cartId.ts';
import type { CartItemId } from './cartItemId.ts';
import type { VariantId } from './variantId.ts';

export interface CartItem {
  cart_id: CartId;
  created_at: string;
  currency: string;
  id: CartItemId;
  quantity: number;
  unit_price: number;
  updated_at: string;
  variant_id: VariantId;
}
