/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryId } from './categoryId.ts';

export interface CatalogCategory {
  display_name: string;
  id: CategoryId;
  slug: string;
}
