/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';

export interface CatalogBrand {
  display_name: string;
  id: BrandId;
}
