/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type CatalogSortOrderParam = typeof CatalogSortOrderParam[keyof typeof CatalogSortOrderParam];


export const CatalogSortOrderParam = {
  asc: 'asc',
  desc: 'desc',
} as const;
