/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type CatalogAvailabilityParam = typeof CatalogAvailabilityParam[keyof typeof CatalogAvailabilityParam];


export const CatalogAvailabilityParam = {
  all: 'all',
  available: 'available',
  out_of_stock: 'out_of_stock',
} as const;
