/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type CatalogSortByParam = typeof CatalogSortByParam[keyof typeof CatalogSortByParam];


export const CatalogSortByParam = {
  name: 'name',
  price: 'price',
  created_at: 'created_at',
} as const;
