/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CatalogBrand } from './catalogBrand.ts';
import type { CatalogCategory } from './catalogCategory.ts';
import type { CatalogPrice } from './catalogPrice.ts';
import type { ProductId } from './productId.ts';

export interface CatalogProduct {
  brand: CatalogBrand;
  category: CatalogCategory;
  created_at: string;
  default_price?: null | CatalogPrice;
  display_name: string;
  id: ProductId;
  is_available: boolean;
  /** @nullable */
  main_image_url?: string | null;
}
