/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type CategoryStatus = typeof CategoryStatus[keyof typeof CategoryStatus];


export const CategoryStatus = {
  active: 'active',
  disable: 'disable',
  archive: 'archive',
} as const;
