/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryId } from './categoryId.ts';

export interface Category {
  created_at: string;
  /** @nullable */
  description?: string | null;
  display_name: string;
  id: CategoryId;
  parent_id?: null | CategoryId;
  slug: string;
}
