/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryId } from './categoryId.ts';

export interface CategorySalesSummary {
  category_id: CategoryId;
  name: string;
  sales_total: number;
  units_sold: number;
}
