/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AddressSnapshot } from './addressSnapshot.ts';

export interface CheckoutCartRequest {
  billing_address: AddressSnapshot;
  /** @nullable */
  comments?: string | null;
  shipping_address: AddressSnapshot;
}
