/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CartId } from './cartId.ts';

export type ClearCartHandlerParams = {
/**
 * Cart ID
 */
cart_id: CartId;
};
