/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface CreateCustomerRequest {
  company_name: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  tax_id: string;
}
