/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CreateVariantPriceRequest } from './createVariantPriceRequest.ts';
import type { CreateVariantPropertyRequest } from './createVariantPropertyRequest.ts';

export interface CreateVariantRequest {
  display_name: string;
  image_url: string;
  prices: CreateVariantPriceRequest[];
  properties: CreateVariantPropertyRequest[];
  sku: string;
}
