/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { InventoryTransactionDestinationType } from './inventoryTransactionDestinationType.ts';
import type { InventoryTransactionSourceType } from './inventoryTransactionSourceType.ts';
import type { InventoryTransactionType } from './inventoryTransactionType.ts';
import type { VariantId } from './variantId.ts';
import type { WarehouseId } from './warehouseId.ts';

export interface CreateInventoryTransactionRequest {
  /** @nullable */
  destination_id?: string | null;
  destination_type?: null | InventoryTransactionDestinationType;
  quantity: number;
  /** @nullable */
  source_id?: string | null;
  source_type?: null | InventoryTransactionSourceType;
  transaction_type: InventoryTransactionType;
  variant_id: VariantId;
  warehouse_id: WarehouseId;
}
