/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CreateVariantImageRequest } from './createVariantImageRequest.ts';
import type { CreateVariantPriceRequest } from './createVariantPriceRequest.ts';
import type { CreateVariantPropertyRequest } from './createVariantPropertyRequest.ts';

export interface CreateVariantRequest {
  /** @nullable */
  description?: string | null;
  display_name: string;
  images: CreateVariantImageRequest[];
  prices: CreateVariantPriceRequest[];
  properties: CreateVariantPropertyRequest[];
  sku: string;
}
