/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface CreateUserRequest {
  email: string;
  father_last_name: string;
  mother_last_name: string;
  name: string;
  password: string;
  username: string;
}
