/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { RoleId } from './roleId.ts';

export interface CreateUserRequest {
  email: string;
  father_last_name: string;
  mother_last_name: string;
  name: string;
  password: string;
  /** @nullable */
  role_ids?: RoleId[] | null;
  username: string;
}
