/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface CreateVariantPropertyRequest {
  property_name: string;
  property_value: string;
}
