/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { File } from './file.ts';

export interface CreateFileResponse {
  /** @minimum 0 */
  expires_in_seconds: number;
  file: File;
  public_url: string;
  upload_url: string;
}
