/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductId } from './productId.ts';

export interface CreateCategoryRequest {
  /** @nullable */
  description?: string | null;
  display_name: string;
  parent_id?: null | ProductId;
  slug: string;
}
