/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PriceType } from './priceType.ts';

export interface CreateVariantPriceRequest {
  amount: number;
  currency: string;
  price_type: PriceType;
}
