/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CreateWarehouseAddressRequest } from './createWarehouseAddressRequest.ts';

export interface CreateWarehouseRequest {
  address: CreateWarehouseAddressRequest;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  description?: string | null;
  name: string;
}
