/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { FileType } from './fileType.ts';

export interface CreateFileRequest {
  checksum: string;
  content_type: string;
  /** @nullable */
  file_name?: string | null;
  file_type: FileType;
  original_filename: string;
  size: number;
}
