/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { VariantId } from './variantId.ts';

export interface CreateSalesOrderLineRequest {
  description: string;
  /** @nullable */
  discount_percent?: number | null;
  quantity: number;
  tax_rate: number;
  unit_price: number;
  variant_id: VariantId;
}
