/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CreateSalesOrderLineWarehouseAllocationRequest } from './createSalesOrderLineWarehouseAllocationRequest.ts';
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { VariantId } from './variantId.ts';

export interface CreateSalesOrderLineRequest {
  description: string;
  line_id?: null | SalesOrderLineId;
  quantity: number;
  tax_rate: number;
  unit_price: number;
  variant_id: VariantId;
  warehouse_allocations: CreateSalesOrderLineWarehouseAllocationRequest[];
}
