/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type CustomerAddressStatus = typeof CustomerAddressStatus[keyof typeof CustomerAddressStatus];


export const CustomerAddressStatus = {
  enable: 'enable',
  disable: 'disable',
  archive: 'archive',
} as const;
