/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CustomerId } from './customerId.ts';

export interface CustomerSalesSummary {
  /** @nullable */
  current_name?: string | null;
  /** @nullable */
  current_status?: string | null;
  customer_id: CustomerId;
  order_count: number;
  sales_total: number;
  /** @nullable */
  snapshot_name?: string | null;
}
