/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface CustomerKpis {
  new: number;
  repeat_purchase_rate: number;
  returning: number;
  total: number;
}
