/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CustomerId } from './customerId.ts';
import type { CustomerStatus } from './customerStatus.ts';
import type { UserId } from './userId.ts';

export interface CustomerResponse {
  company_name: string;
  created_at: string;
  /** @nullable */
  email?: string | null;
  id: CustomerId;
  /** @nullable */
  phone?: string | null;
  status: CustomerStatus;
  tax_id: string;
  updated_at: string;
  user_id: UserId;
}
