/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CustomerId } from './customerId.ts';

export interface CustomerSnapshot {
  customer_id: CustomerId;
  name: string;
}
