/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface CustomerConcentration {
  top_10_sales_share: number;
  top_10_sales_total: number;
  top_5_sales_share: number;
  top_5_sales_total: number;
}
