/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AddressId } from './addressId.ts';
import type { CustomerAddressId } from './customerAddressId.ts';
import type { CustomerAddressStatus } from './customerAddressStatus.ts';
import type { CustomerId } from './customerId.ts';

export interface CustomerAddress {
  address_id: AddressId;
  contact_name: string;
  created_at: string;
  customer_id: CustomerId;
  id: CustomerAddressId;
  is_default_billing: boolean;
  is_default_shipping: boolean;
  phone: string;
  status: CustomerAddressStatus;
  updated_at: string;
}
