/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { DeleteFileRequestDeleteType } from './deleteFileRequestDeleteType.ts';

export type DeleteFileRequestParams = {
delete_type: DeleteFileRequestDeleteType;
};
