/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type DeleteKind = typeof DeleteKind[keyof typeof DeleteKind];


export const DeleteKind = {
  soft: 'soft',
  hard: 'hard',
} as const;
