/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type DeleteFileRequestDeleteType = typeof DeleteFileRequestDeleteType[keyof typeof DeleteFileRequestDeleteType];


export const DeleteFileRequestDeleteType = {
  soft: 'soft',
  hard: 'hard',
} as const;
