/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { DiscountSourceSummary } from './discountSourceSummary.ts';
import type { PromotionDiscountSummary } from './promotionDiscountSummary.ts';

export interface DiscountBreakdown {
  attributed_total: number;
  by_source: DiscountSourceSummary[];
  promotions: PromotionDiscountSummary[];
  reconciled: boolean;
  unattributed_total: number;
}
