/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type DiscountValue = {
  percentage: number;
} | {
  /**
     * @minItems 2
     * @maxItems 2
     */
  fixed_amount: { [key: string]: unknown }[];
};
