/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { DiscountSource } from './discountSource.ts';

export interface DiscountSourceSummary {
  adjustment_count: number;
  amount: number;
  line_count: number;
  order_count: number;
  source: DiscountSource;
}
