/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type DiscountSource = typeof DiscountSource[keyof typeof DiscountSource];


export const DiscountSource = {
  promotion: 'promotion',
  manual: 'manual',
  unknown: 'unknown',
} as const;
