/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { SalesOrderStatus } from './salesOrderStatus.ts';

export interface DispatchSalesOrderLineResult {
  dispatched_quantity: number;
  fully_dispatched: boolean;
  remaining_quantity: number;
  sales_order_line_id: SalesOrderLineId;
  sales_order_status: SalesOrderStatus;
}
