/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrder } from './salesOrder.ts';
import type { Shipment } from './shipment.ts';
import type { ShipmentLine } from './shipmentLine.ts';

export interface DispatchSalesOrderLineResult {
  sales_order: SalesOrder;
  shipment: Shipment;
  shipment_line: ShipmentLine;
}
