/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { SalesOrderStatus } from './salesOrderStatus.ts';
import type { WarehouseId } from './warehouseId.ts';

export interface DispatchSalesOrderLineResult {
  allocation_dispatched_quantity: number;
  allocation_remaining_quantity: number;
  fully_dispatched: boolean;
  line_dispatched_quantity: number;
  line_remaining_quantity: number;
  sales_order_line_id: SalesOrderLineId;
  sales_order_status: SalesOrderStatus;
  warehouse_id: WarehouseId;
}
