/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type EntityType = typeof EntityType[keyof typeof EntityType];


export const EntityType = {
  product: 'product',
  order: 'order',
  invoice: 'invoice',
  customer: 'customer',
  warehouse: 'warehouse',
} as const;
