/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface ErrorResponse {
  content?: unknown;
  /** @nullable */
  message?: string | null;
  type: string;
}
