/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type FileStatus = typeof FileStatus[keyof typeof FileStatus];


export const FileStatus = {
  active: 'active',
  archive: 'archive',
  delete: 'delete',
  hard_delete: 'hard_delete',
} as const;
