/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { EntityType } from './entityType.ts';
import type { FileAssociationId } from './fileAssociationId.ts';
import type { FileId } from './fileId.ts';
import type { RelationshipType } from './relationshipType.ts';

export interface FileAssociation {
  created_at: string;
  entity_id: string;
  entity_type: EntityType;
  file_id: FileId;
  id: FileAssociationId;
  relationship_type: RelationshipType;
}
