/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type FileType = typeof FileType[keyof typeof FileType];


export const FileType = {
  public: 'public',
  private: 'private',
} as const;
