/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { FileId } from './fileId.ts';
import type { FileStatus } from './fileStatus.ts';
import type { FileType } from './fileType.ts';

export interface File {
  bucket: string;
  checksum: string;
  content_type: string;
  created_at: string;
  /** @nullable */
  file_name?: string | null;
  file_type: FileType;
  id: FileId;
  object_key: string;
  original_filename: string;
  size: number;
  status: FileStatus;
  storage_provider: string;
}
