/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type FulfillState = typeof FulfillState[keyof typeof FulfillState];


export const FulfillState = {
  picked: 'picked',
} as const;
