/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CycleTimeKpi } from './cycleTimeKpi.ts';

export interface FunnelCycleTimes {
  confirmed_to_closed: CycleTimeKpi;
  confirmed_to_fulfilled: CycleTimeKpi;
  fulfilled_to_closed: CycleTimeKpi;
  quote_to_confirmed: CycleTimeKpi;
}
