/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ConversionKpi } from './conversionKpi.ts';

export interface FunnelConversions {
  confirmed_to_closed: ConversionKpi;
  confirmed_to_fulfilled: ConversionKpi;
  fulfilled_to_closed: ConversionKpi;
  quote_to_confirmed: ConversionKpi;
}
