/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type GetCategoriesRequestOrder = typeof GetCategoriesRequestOrder[keyof typeof GetCategoriesRequestOrder];


export const GetCategoriesRequestOrder = {
  null: null,
  asc: 'asc',
  desc: 'desc',
} as const;
