/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CartId } from './cartId.ts';
import type { CartItemResponse } from './cartItemResponse.ts';

export interface GetCartResponse {
  currency: string;
  grand_total: number;
  id: CartId;
  item_count: number;
  items: CartItemResponse[];
  subtotal: number;
  tax_rate: number;
  tax_total: number;
}
