/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { GetCategoriesRequestOrder } from './getCategoriesRequestOrder.ts';

export type GetCategoriesRequestParams = {
/**
 * Case-insensitive partial match against the category display name or description.
 * @nullable
 */
display_name?: string | null;
/**
 * Sort by creation date: `asc` for oldest first, `desc` for newest first.
 */
order?: GetCategoriesRequestOrder;
};
