/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type GetDownloadUrlRequestParams = {
/**
 * @minimum 0
 */
expires_in_seconds?: number;
};
