/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type GetSalesSummaryRequestParams = {
/**
 * First included business date, formatted as YYYY-MM-DD.
 */
from?: string;
/**
 * Last included business date, formatted as YYYY-MM-DD.
 */
to?: string;
};
