/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Permission } from './permission.ts';
import type { UserId } from './userId.ts';

export interface GetUserPermissionsResponse {
  permissions: Permission[];
  user_id: UserId;
}
