/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type InventoryTransactionType = typeof InventoryTransactionType[keyof typeof InventoryTransactionType];


export const InventoryTransactionType = {
  correction_addition: 'correction_addition',
  correction_substraction: 'correction_substraction',
  available: 'available',
  reserved: 'reserved',
  blocked: 'blocked',
  in_transit: 'in_transit',
} as const;
