/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { VariantId } from './variantId.ts';
import type { WarehouseId } from './warehouseId.ts';

export interface InventoryItemResponse {
  total_quantity: number;
  variant_id: VariantId;
  variant_name: string;
  variant_sku: string;
  warehouse_id: WarehouseId;
  warehouse_name: string;
}
