/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type InventoryTransactionSourceType = typeof InventoryTransactionSourceType[keyof typeof InventoryTransactionSourceType];


export const InventoryTransactionSourceType = {
  warehouse: 'warehouse',
  customer: 'customer',
  supplier: 'supplier',
  store: 'store',
} as const;
