/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type InventoryTransactionDestinationType = typeof InventoryTransactionDestinationType[keyof typeof InventoryTransactionDestinationType];


export const InventoryTransactionDestinationType = {
  warehouse: 'warehouse',
  customer: 'customer',
  supplier: 'supplier',
  store: 'store',
} as const;
