/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId.ts';

export type ListAuditEventsRequestParams = {
actor?: UserId;
action?: string;
entity_type?: string;
entity_id?: string;
date_from?: string;
date_to?: string;
page?: number;
limit?: number;
};
