/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type ListMySalesOrdersRequestParams = {
status?: string;
order_number?: string;
page?: number;
limit?: number;
};
