/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductListItem } from './productListItem.ts';

export interface ListProductsResponse {
  data: ProductListItem[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  page: number;
  total: number;
}
