/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserWithRolesResponse } from './userWithRolesResponse.ts';

export interface ListUsersResponse {
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  total: number;
  users: UserWithRolesResponse[];
}
