/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type ListBrandsRequestOrder = typeof ListBrandsRequestOrder[keyof typeof ListBrandsRequestOrder];


export const ListBrandsRequestOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
