/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Permission } from './permission.ts';

export interface ListPermissionsResponse {
  permissions: Permission[];
}
