/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';
import type { CatalogAvailabilityParam } from './catalogAvailabilityParam.ts';
import type { CatalogSortByParam } from './catalogSortByParam.ts';
import type { CatalogSortOrderParam } from './catalogSortOrderParam.ts';
import type { CategoryId } from './categoryId.ts';

export type ListCatalogProductsRequestParams = {
category_id?: CategoryId;
brand_id?: BrandId;
search?: string;
sort_by?: CatalogSortByParam;
sort_order?: CatalogSortOrderParam;
availability?: CatalogAvailabilityParam;
/**
 * @minimum 0
 */
page?: number;
/**
 * @minimum 0
 */
limit?: number;
};
