/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type ListSalesOrdersRequestParams = {
status?: string;
order_number?: string;
customer_username?: string;
customer_company_name?: string;
order_date_from?: string;
order_date_to?: string;
grand_total_min?: number;
grand_total_max?: number;
shipping_state?: string;
shipping_country?: string;
tag_ids?: string;
page?: number;
limit?: number;
};
