/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductStatus } from './productStatus.ts';

export type ListProductsRequestParams = {
status?: ProductStatus;
search?: string;
/**
 * @minimum 0
 */
page?: number;
/**
 * @minimum 0
 */
limit?: number;
};
