/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ListBrandsRequestOrder } from './listBrandsRequestOrder.ts';

export type ListBrandsRequestParams = {
page?: number;
limit?: number;
display_name?: string;
order?: ListBrandsRequestOrder;
};
