/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { OrderTagStatus } from './orderTagStatus.ts';

export type ListTagsRequestParams = {
status?: OrderTagStatus;
};
