/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { LocalityId } from './localityId.ts';
import type { StateId } from './stateId.ts';

export interface Locality {
  created_at: string;
  display_name: string;
  id: LocalityId;
  state_id: StateId;
}
