/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponse } from './userResponse.ts';

export interface LoginResponse {
  session_id: string;
  user: UserResponse;
}
