/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type OrderTagStatus = typeof OrderTagStatus[keyof typeof OrderTagStatus];


export const OrderTagStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
