/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CancellationCounts } from './cancellationCounts.ts';
import type { FunnelConversions } from './funnelConversions.ts';
import type { FunnelCycleTimes } from './funnelCycleTimes.ts';
import type { StatusEntryCounts } from './statusEntryCounts.ts';

export interface OrderFunnel {
  cancellations: CancellationCounts;
  conversions: FunnelConversions;
  cycle_times: FunnelCycleTimes;
  date_basis: string;
  from: string;
  status_entries: StatusEntryCounts;
  timezone: string;
  to: string;
}
