/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AddressSnapshot } from './addressSnapshot.ts';
import type { CustomerSnapshot } from './customerSnapshot.ts';
import type { OrderTag } from './orderTag.ts';
import type { SalesOrderId } from './salesOrderId.ts';
import type { SalesOrderStatus } from './salesOrderStatus.ts';

export type PaginatedSalesOrderSummaryViewDataItem = {
  billing_address: AddressSnapshot;
  /** @nullable */
  comments?: string | null;
  created_at: string;
  customer: CustomerSnapshot;
  discount_total: number;
  grand_total: number;
  id: SalesOrderId;
  order_date: string;
  order_number: string;
  shipping_address: AddressSnapshot;
  status: SalesOrderStatus;
  subtotal: number;
  tags: OrderTag[];
  tax_total: number;
  updated_at: string;
};
