/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaginatedAuditEventResponseDataItem } from './paginatedAuditEventResponseDataItem.ts';

export interface PaginatedAuditEventResponse {
  data: PaginatedAuditEventResponseDataItem[];
  limit: number;
  page: number;
  total: number;
}
