/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaginatedSalesOrderSummaryDataItem } from './paginatedSalesOrderSummaryDataItem.ts';

export interface PaginatedSalesOrderSummary {
  data: PaginatedSalesOrderSummaryDataItem[];
  limit: number;
  page: number;
  total: number;
}
