/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaginatedSalesOrderSummaryViewDataItem } from './paginatedSalesOrderSummaryViewDataItem.ts';

export interface PaginatedSalesOrderSummaryView {
  data: PaginatedSalesOrderSummaryViewDataItem[];
  limit: number;
  page: number;
  total: number;
}
