/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaginatedCustomerSummaryDataItem } from './paginatedCustomerSummaryDataItem.ts';

export interface PaginatedCustomerSummary {
  data: PaginatedCustomerSummaryDataItem[];
  limit: number;
  page: number;
  total: number;
}
