/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';
import type { BrandStatus } from './brandStatus.ts';

export type PaginatedBrandDataItem = {
  created_at: string;
  display_name: string;
  id: BrandId;
  image_url: string;
  status: BrandStatus;
};
