/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CustomerId } from './customerId.ts';
import type { CustomerStatus } from './customerStatus.ts';

export type PaginatedCustomerSummaryDataItem = {
  company_name: string;
  /** @nullable */
  email?: string | null;
  id: CustomerId;
  /** @nullable */
  tax_id?: string | null;
  status: CustomerStatus;
  /** @nullable */
  username?: string | null;
};
