/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentTermId } from './paymentTermId.ts';

export interface PaymentTermSalesKpi {
  name: string;
  order_count: number;
  payment_term_id: PaymentTermId;
  sales_share: number;
  sales_total: number;
}
