/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type PaymentTermType = typeof PaymentTermType[keyof typeof PaymentTermType];


export const PaymentTermType = {
  net: 'net',
  due_on_receipt: 'due_on_receipt',
} as const;
