/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentTermId } from './paymentTermId.ts';
import type { PaymentTermType } from './paymentTermType.ts';

export interface PaymentTerm {
  created_at: string;
  /** @nullable */
  days_until_due?: number | null;
  /** @nullable */
  description?: string | null;
  id: PaymentTermId;
  is_active: boolean;
  name: string;
  type: PaymentTermType;
  updated_at: string;
}
