/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type PermissionStatus = typeof PermissionStatus[keyof typeof PermissionStatus];


export const PermissionStatus = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;
