/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionId } from './permissionId.ts';
import type { RoleStatus } from './roleStatus.ts';

export interface Permission {
  created_at: string;
  /** @nullable */
  description?: string | null;
  display_name: string;
  id: PermissionId;
  slug: string;
  status: RoleStatus;
}
