/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type PermissionStatus = typeof PermissionStatus[keyof typeof PermissionStatus];


export const PermissionStatus = {
  enable: 'enable',
  disable: 'disable',
  archive: 'archive',
} as const;
