/**
<<<<<<< HEAD
 * Generated by orval v8.20.0 🍺
=======
 * Generated by orval v8.23.0 🍺
>>>>>>> main
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionId } from './permissionId.ts';
import type { PermissionStatus } from './permissionStatus.ts';

export interface Permission {
  created_at: string;
  /** @nullable */
  description?: string | null;
  display_name: string;
  id: PermissionId;
  slug: string;
  status: PermissionStatus;
}
