/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderId } from './salesOrderId.ts';

export interface PickFulfillmentOrderRequest {
  order_id?: null | SalesOrderId;
}
