/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type PriceType = typeof PriceType[keyof typeof PriceType];


export const PriceType = {
  regular: 'regular',
  sale: 'sale',
  wholesale: 'wholesale',
  acquisition_cost: 'acquisition_cost',
} as const;
