/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';
import type { CategoryId } from './categoryId.ts';
import type { ProductId } from './productId.ts';
import type { ProductStatus } from './productStatus.ts';

export interface ProductListItem {
  brand_id: BrandId;
  brand_name: string;
  category_id: CategoryId;
  category_name: string;
  created_at: string;
  /** @nullable */
  description?: string | null;
  display_name: string;
  id: ProductId;
  status: ProductStatus;
  updated_at: string;
}
