/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductId } from './productId.ts';

export interface ProductSalesSummary {
  name: string;
  product_id: ProductId;
  sales_total: number;
  units_sold: number;
}
