/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Brand } from './brand.ts';
import type { Category } from './category.ts';
import type { ProductId } from './productId.ts';
import type { ProductStatus } from './productStatus.ts';

export interface ProductResponse {
  brand: Brand;
  category: Category;
  created_at: string;
  /** @nullable */
  description?: string | null;
  display_name: string;
  id: ProductId;
  status: ProductStatus;
  updated_at: string;
}
