/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PromotionRuleId } from './promotionRuleId.ts';
import type { RuleAttribute } from './ruleAttribute.ts';
import type { RuleOperator } from './ruleOperator.ts';
import type { RuleValue } from './ruleValue.ts';

export interface PromotionRule {
  attribute: RuleAttribute;
  id: PromotionRuleId;
  operator: RuleOperator;
  values: RuleValue[];
}
