/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PromotionId } from './promotionId.ts';

export interface PromotionDiscountSummary {
  adjustment_count: number;
  amount: number;
  /** @nullable */
  current_code?: string | null;
  /** @nullable */
  current_status?: string | null;
  line_count: number;
  order_count: number;
  /** @nullable */
  promotion_code?: string | null;
  promotion_deleted: boolean;
  promotion_id?: null | PromotionId;
}
