/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type RelationshipType = typeof RelationshipType[keyof typeof RelationshipType];


export const RelationshipType = {
  primary_image: 'primary_image',
  image: 'image',
} as const;
