/**
<<<<<<< HEAD
 * Generated by orval v8.20.0 🍺
=======
 * Generated by orval v8.23.0 🍺
>>>>>>> main
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Permission } from './permission.ts';

export interface RemovePermissionsResponse {
  permissions: Permission[];
}
