/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { RoleId } from './roleId.ts';
import type { UserId } from './userId.ts';

export interface RemoveUserRoleResponse {
  role_id: RoleId;
  user_id: UserId;
}
