/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { VariantId } from './variantId.ts';

/**
 * Snapshot of a sales order line embedded inside audit events.
 *
 * Field order is part of the public API so that consumers can rely on a
 * stable representation.
 */
export interface SalesOrderUpdatedAuditLine {
  description: string;
  line_id: SalesOrderLineId;
  line_total: number;
  quantity: number;
  unit_price: number;
  variant_id: VariantId;
}
