/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductId } from './productId.ts';
import type { SalesOrderLineAdjustment } from './salesOrderLineAdjustment.ts';
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { VariantId } from './variantId.ts';

export interface SalesOrderLine {
  adjustments: SalesOrderLineAdjustment[];
  description: string;
  discount_amount: number;
  dispatched_quantity: number;
  id: SalesOrderLineId;
  line_number: number;
  line_total: number;
  product_id: ProductId;
  quantity: number;
  tax_amount: number;
  tax_rate: number;
  unit_price: number;
  variant_id: VariantId;
}
