/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AdjustmentSource } from './adjustmentSource.ts';
import type { SalesOrderLineAdjustmentId } from './salesOrderLineAdjustmentId.ts';

export interface SalesOrderLineAdjustment {
  amount: number;
  /** @nullable */
  description?: string | null;
  id: SalesOrderLineAdjustmentId;
  source: AdjustmentSource;
}
