/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CategorySalesSummary } from './categorySalesSummary.ts';
import type { CustomerSalesSummary } from './customerSalesSummary.ts';
import type { DiscountBreakdown } from './discountBreakdown.ts';
import type { ProductSalesSummary } from './productSalesSummary.ts';
import type { SellerSalesSummary } from './sellerSalesSummary.ts';
import type { UnassignedSalesSummary } from './unassignedSalesSummary.ts';

export interface SalesSummary {
  cancelled_after_confirmation_order_count: number;
  categories: CategorySalesSummary[];
  customers: CustomerSalesSummary[];
  discount_breakdown: DiscountBreakdown;
  discount_total: number;
  from: string;
  order_count: number;
  products: ProductSalesSummary[];
  sales_total: number;
  sellers: SellerSalesSummary[];
  subtotal: number;
  tax_total: number;
  timezone: string;
  to: string;
  unassigned_seller: UnassignedSalesSummary;
  units_sold: number;
}
