/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { VariantId } from './variantId.ts';

/**
 * Entry in the `modified_lines` array. `changes` is an open map keyed by the
 * field name (`quantity`, `unit_price`, `discount_amount`, `description`,
 * `variant_id`) with `{from, to}` payloads describing the previous and new
 * value.
 */
export interface SalesOrderUpdatedAuditModifiedLine {
  changes: unknown;
  description: string;
  line_id: SalesOrderLineId;
  variant_id: VariantId;
}
