/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { AuditFromToAddress } from './auditFromToAddress.ts';
import type { AuditFromToI64 } from './auditFromToI64.ts';
import type { AuditFromToPaymentTermId } from './auditFromToPaymentTermId.ts';
import type { SalesOrderUpdatedAuditLine } from './salesOrderUpdatedAuditLine.ts';
import type { SalesOrderUpdatedAuditModifiedLine } from './salesOrderUpdatedAuditModifiedLine.ts';

/**
 * Shape of the `data` payload for `sales_order.updated` audit events.
 *
 * `added_lines` lists lines that did not exist before the update, while
 * `removed_lines` lists lines that were dropped, and `modified_lines` lists
 * the lines whose tracked fields changed between the previous and new
 * versions of the order. The aggregate `grand_total` and `line_count` fields
 * are kept for backwards compatibility.
 *
 * The optional `billing_address`, `shipping_address` and `payment_term_id`
 * fields are emitted only when those tracked values actually changed between
 * the previous and new versions of the order.
 */
export interface SalesOrderUpdatedAuditData {
  added_lines?: SalesOrderUpdatedAuditLine[];
  billing_address?: null | AuditFromToAddress;
  grand_total: AuditFromToI64;
  line_count: AuditFromToI64;
  modified_lines?: SalesOrderUpdatedAuditModifiedLine[];
  payment_term_id?: null | AuditFromToPaymentTermId;
  removed_lines?: SalesOrderUpdatedAuditLine[];
  shipping_address?: null | AuditFromToAddress;
}
