/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId.ts';

export interface SellerSalesSummary {
  /** @nullable */
  current_name?: string | null;
  /** @nullable */
  current_status?: string | null;
  order_count: number;
  sales_total: number;
  seller_id: UserId;
}
