/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId.ts';

export interface SessionUser {
  email: string;
  session_id: string;
  user_id: UserId;
  username: string;
}
