/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderId } from './salesOrderId.ts';
import type { ShipmentId } from './shipmentId.ts';
import type { ShipmentStatus } from './shipmentStatus.ts';

export interface Shipment {
  created_at: string;
  id: ShipmentId;
  sales_order_id: SalesOrderId;
  status: ShipmentStatus;
  updated_at: string;
}
