/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type ShipmentStatus = typeof ShipmentStatus[keyof typeof ShipmentStatus];


export const ShipmentStatus = {
  draft: 'draft',
  ready: 'ready',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const;
