/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderLineId } from './salesOrderLineId.ts';
import type { ShipmentId } from './shipmentId.ts';
import type { ShipmentLineId } from './shipmentLineId.ts';

export interface ShipmentLine {
  created_at: string;
  id: ShipmentLineId;
  quantity: number;
  sales_order_line_id: SalesOrderLineId;
  shipment_id: ShipmentId;
}
