/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type SortOrderParam = typeof SortOrderParam[keyof typeof SortOrderParam];


export const SortOrderParam = {
  asc: 'asc',
  desc: 'desc',
} as const;
