/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type Stacking = 'not_combinable' | {
  combinable: {
  /** @minimum 0 */
  priority: number;
};
};
