/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface StatusEntryCounts {
  cancelled: number;
  closed: number;
  confirmed: number;
  draft: number;
  fulfilled: number;
  partially_fulfilled: number;
  quote: number;
}
