/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { StateId } from './stateId.ts';

export interface State {
  created_at: string;
  display_name: string;
  id: StateId;
}
