/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PriceType } from './priceType.ts';
import type { VariantStatus } from './variantStatus.ts';

export interface UpdateVariantPriceRequest {
  amount: number;
  currency: string;
  price_type: PriceType;
  status: VariantStatus;
}
