/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { SalesOrderStatus } from './salesOrderStatus.ts';

export interface UpdateSalesOrderStatusRequest {
  status: SalesOrderStatus;
}
