/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateUserProfileRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  father_last_name?: string | null;
  /** @nullable */
  mother_last_name?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
}
