/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { RoleStatus } from './roleStatus.ts';

export interface UpdateRoleRequest {
  /** @nullable */
  display_name?: string | null;
  /** @nullable */
  slug?: string | null;
  status?: null | RoleStatus;
}
