/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { RoleStatus } from './roleStatus.ts';

export interface UpdateRoleRequest {
  display_name: string;
  slug: string;
  status: RoleStatus;
}
