/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductStatus } from './productStatus.ts';

export interface UpdateProductRequest {
  /** @nullable */
  brand_name?: string | null;
  /** @nullable */
  category_name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  display_name?: string | null;
  status?: null | ProductStatus;
}
