/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateVariantPriceRequest } from './updateVariantPriceRequest.ts';
import type { UpdateVariantPropertyRequest } from './updateVariantPropertyRequest.ts';
import type { VariantStatus } from './variantStatus.ts';

export interface UpdateVariantRequest {
  /** @nullable */
  display_name?: string | null;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  prices?: UpdateVariantPriceRequest[] | null;
  /** @nullable */
  properties?: UpdateVariantPropertyRequest[] | null;
  /** @nullable */
  sku?: string | null;
  status?: null | VariantStatus;
}
