/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Permission } from './permission.ts';

export interface UpdatePermissionResponse {
  permission: Permission;
}
