/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryId } from './categoryId.ts';

export interface UpdateCategoryRequest {
  /** @nullable */
  description?: string | null;
  display_name: string;
  parent_id?: null | CategoryId;
  slug: string;
}
