/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { OrderTagStatus } from './orderTagStatus.ts';

export interface UpdateTagRequest {
  /** @nullable */
  color?: string | null;
  display_name: string;
  slug: string;
  status: OrderTagStatus;
}
