/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';
import type { CategoryId } from './categoryId.ts';
import type { ProductStatus } from './productStatus.ts';

export interface UpdateProductRequest {
  brand_id: BrandId;
  category_id: CategoryId;
  /** @nullable */
  description?: string | null;
  display_name: string;
  status: ProductStatus;
}
