/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateCustomerAddressRequest {
  address: string;
  city: string;
  contact_name: string;
  country: string;
  phone: string;
  postal_code: string;
  state: string;
}
