/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { VariantImageId } from './variantImageId.ts';
import type { VariantStatus } from './variantStatus.ts';

export interface UpdateVariantImageRequest {
  id?: null | VariantImageId;
  image_index: number;
  image_url: string;
  status?: VariantStatus;
}
