/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { VariantStatus } from './variantStatus.ts';

export interface UpdateVariantPropertyRequest {
  property_name: string;
  property_value: string;
  status?: VariantStatus;
}
