/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { CartItem } from './cartItem.ts';

export interface UpdateCartItemResponse {
  item?: null | CartItem;
}
