/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { BrandId } from './brandId.ts';
import type { CategoryId } from './categoryId.ts';
import type { ProductStatus } from './productStatus.ts';

export interface UpdateProductRequest {
  brand_id?: null | BrandId;
  category_id?: null | CategoryId;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  display_name?: string | null;
  status?: null | ProductStatus;
}
