/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role.ts';
import type { UserResponse } from './userResponse.ts';

export type UserWithRolesResponse = UserResponse & {
  roles: Role[];
};
