/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { PasswordHash } from './passwordHash.ts';
import type { UserId } from './userId.ts';
import type { UserStatus } from './userStatus.ts';

export interface User {
  created_at: string;
  email: string;
  father_last_name: string;
  id: UserId;
  mother_last_name: string;
  name: string;
  password: PasswordHash;
  status: UserStatus;
  username: string;
}
