/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId.ts';
import type { UserStatus } from './userStatus.ts';

export interface UserResponse {
  created_at: string;
  email: string;
  father_last_name: string;
  id: UserId;
  /** @nullable */
  mother_last_name?: string | null;
  name: string;
  status: UserStatus;
  username: string;
}
