/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type UserViewParam = typeof UserViewParam[keyof typeof UserViewParam];


export const UserViewParam = {
  client: 'client',
  staff: 'staff',
  archived: 'archived',
} as const;
