/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { VariantId } from './variantId.ts';
import type { VariantPropertyId } from './variantPropertyId.ts';
import type { VariantStatus } from './variantStatus.ts';

export interface VariantProperty {
  created_at: string;
  id: VariantPropertyId;
  property_name: string;
  property_value: string;
  status: VariantStatus;
  variant_id: VariantId;
}
