/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { VariantId } from './variantId.ts';

export interface VariantSalesKpi {
  order_count: number;
  product_name: string;
  sales_total: number;
  sku: string;
  units_sold: number;
  variant_id: VariantId;
  variant_name: string;
}
