/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type VariantStatus = typeof VariantStatus[keyof typeof VariantStatus];


export const VariantStatus = {
  enable: 'enable',
  disable: 'disable',
  archive: 'archive',
} as const;
