/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { ProductId } from './productId.ts';
import type { VariantId } from './variantId.ts';
import type { VariantPrice } from './variantPrice.ts';
import type { VariantProperty } from './variantProperty.ts';
import type { VariantStatus } from './variantStatus.ts';

export interface Variant {
  created_at: string;
  display_name: string;
  id: VariantId;
  image_url: string;
  prices: VariantPrice[];
  product_id: ProductId;
  properties: VariantProperty[];
  sku: string;
  status: VariantStatus;
  updated_at: string;
}
