/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { FileId } from './fileId.ts';
import type { VariantId } from './variantId.ts';
import type { VariantImageId } from './variantImageId.ts';
import type { VariantStatus } from './variantStatus.ts';

export interface VariantImage {
  created_at: string;
  file_id?: null | FileId;
  id: VariantImageId;
  image_index: number;
  image_url: string;
  status: VariantStatus;
  updated_at: string;
  variant_id: VariantId;
}
