/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type WarehouseStatus = typeof WarehouseStatus[keyof typeof WarehouseStatus];


export const WarehouseStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
