/**
<<<<<<< HEAD
 * Generated by orval v8.20.0 🍺
=======
 * Generated by orval v8.23.0 🍺
>>>>>>> main
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type { Address } from './address.ts';
import type { WarehouseId } from './warehouseId.ts';
import type { WarehouseStatus } from './warehouseStatus.ts';

export interface WarehouseResponse {
  address: Address;
  /** @nullable */
  code?: string | null;
  created_at: string;
  /** @nullable */
  description?: string | null;
  id: WarehouseId;
  name: string;
  status: WarehouseStatus;
  updated_at: string;
}
