/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */

export type WarehouseStatus = typeof WarehouseStatus[keyof typeof WarehouseStatus];


export const WarehouseStatus = {
  enable: 'enable',
  disable: 'disable',
  archive: 'archive',
} as const;
