/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  Category,
  CreateCategoryRequest,
  CreateRoleRequest,
  CreateRoleResponse,
  DeleteRoleResponse,
  ErrorResponse,
  ListRolesResponse,
  RoleId,
  UpdateRoleRequest,
  UpdateRoleResponse
} from './schemas';

export type createCategoryRequestResponse201 = {
  data: Category
  status: 201
}

export type createCategoryRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createCategoryRequestResponse500 = {
  data: void
  status: 500
}

export type createCategoryRequestResponseSuccess = (createCategoryRequestResponse201) & {
  headers: Headers;
};
export type createCategoryRequestResponseError = (createCategoryRequestResponse400 | createCategoryRequestResponse500) & {
  headers: Headers;
};

export type createCategoryRequestResponse = (createCategoryRequestResponseSuccess | createCategoryRequestResponseError)

export const getCreateCategoryRequestUrl = () => {



  return `http://localhost:8080/api/v1/products/categories`
}

export const createCategoryRequest = async (createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<createCategoryRequestResponse> => {

  const res = await fetch(getCreateCategoryRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCategoryRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createCategoryRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCategoryRequestResponse
}



export const getCreateCategoryRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateCategoryRequest }) => {
    return createCategoryRequest(arg, options);
  }
}
export const getCreateCategoryRequestMutationKey = () => [`http://localhost:8080/api/v1/products/categories`] as const;

export type CreateCategoryRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createCategoryRequest>>>

export const useCreateCategoryRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createCategoryRequest>>, TError, Key, CreateCategoryRequest, Awaited<ReturnType<typeof createCategoryRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateCategoryRequestMutationKey();
  const swrFn = getCreateCategoryRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type listRolesHandlerResponse200 = {
  data: ListRolesResponse
  status: 200
}

export type listRolesHandlerResponse500 = {
  data: void
  status: 500
}

export type listRolesHandlerResponseSuccess = (listRolesHandlerResponse200) & {
  headers: Headers;
};
export type listRolesHandlerResponseError = (listRolesHandlerResponse500) & {
  headers: Headers;
};

export type listRolesHandlerResponse = (listRolesHandlerResponseSuccess | listRolesHandlerResponseError)

export const getListRolesHandlerUrl = () => {



  return `http://localhost:8080/api/v1/rbac/roles`
}

export const listRolesHandler = async ( options?: RequestInit): Promise<listRolesHandlerResponse> => {

  const res = await fetch(getListRolesHandlerUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listRolesHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listRolesHandlerResponse
}



export const getListRolesHandlerKey = () => [`http://localhost:8080/api/v1/rbac/roles`] as const;

export type ListRolesHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof listRolesHandler>>>

export const useListRolesHandler = <TError = Promise<void>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listRolesHandler>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListRolesHandlerKey() : null);
  const swrFn = () => listRolesHandler(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createRoleHandlerResponse201 = {
  data: CreateRoleResponse
  status: 201
}

export type createRoleHandlerResponse422 = {
  data: void
  status: 422
}

export type createRoleHandlerResponse500 = {
  data: void
  status: 500
}

export type createRoleHandlerResponseSuccess = (createRoleHandlerResponse201) & {
  headers: Headers;
};
export type createRoleHandlerResponseError = (createRoleHandlerResponse422 | createRoleHandlerResponse500) & {
  headers: Headers;
};

export type createRoleHandlerResponse = (createRoleHandlerResponseSuccess | createRoleHandlerResponseError)

export const getCreateRoleHandlerUrl = () => {



  return `http://localhost:8080/api/v1/rbac/roles`
}

export const createRoleHandler = async (createRoleRequest: CreateRoleRequest, options?: RequestInit): Promise<createRoleHandlerResponse> => {

  const res = await fetch(getCreateRoleHandlerUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRoleHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRoleHandlerResponse
}



export const getCreateRoleHandlerMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateRoleRequest }) => {
    return createRoleHandler(arg, options);
  }
}
export const getCreateRoleHandlerMutationKey = () => [`http://localhost:8080/api/v1/rbac/roles`] as const;

export type CreateRoleHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof createRoleHandler>>>

export const useCreateRoleHandler = <TError = Promise<void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createRoleHandler>>, TError, Key, CreateRoleRequest, Awaited<ReturnType<typeof createRoleHandler>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRoleHandlerMutationKey();
  const swrFn = getCreateRoleHandlerMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type updateRoleHandlerResponse200 = {
  data: UpdateRoleResponse
  status: 200
}

export type updateRoleHandlerResponse404 = {
  data: void
  status: 404
}

export type updateRoleHandlerResponse422 = {
  data: void
  status: 422
}

export type updateRoleHandlerResponse500 = {
  data: void
  status: 500
}

export type updateRoleHandlerResponseSuccess = (updateRoleHandlerResponse200) & {
  headers: Headers;
};
export type updateRoleHandlerResponseError = (updateRoleHandlerResponse404 | updateRoleHandlerResponse422 | updateRoleHandlerResponse500) & {
  headers: Headers;
};

export type updateRoleHandlerResponse = (updateRoleHandlerResponseSuccess | updateRoleHandlerResponseError)

export const getUpdateRoleHandlerUrl = (roleId: RoleId,) => {



  return `http://localhost:8080/api/v1/rbac/roles/${roleId}`
}

export const updateRoleHandler = async (roleId: RoleId,
    updateRoleRequest: UpdateRoleRequest, options?: RequestInit): Promise<updateRoleHandlerResponse> => {

  const res = await fetch(getUpdateRoleHandlerUrl(roleId),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateRoleHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateRoleHandlerResponse
}



export const getUpdateRoleHandlerMutationFetcher = (roleId: RoleId, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateRoleRequest }) => {
    return updateRoleHandler(roleId, arg, options);
  }
}
export const getUpdateRoleHandlerMutationKey = (roleId: RoleId,) => [`http://localhost:8080/api/v1/rbac/roles/${roleId}`] as const;

export type UpdateRoleHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoleHandler>>>

export const useUpdateRoleHandler = <TError = Promise<void>>(
  roleId: RoleId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateRoleHandler>>, TError, Key, UpdateRoleRequest, Awaited<ReturnType<typeof updateRoleHandler>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateRoleHandlerMutationKey(roleId);
  const swrFn = getUpdateRoleHandlerMutationFetcher(roleId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type deleteRoleHandlerResponse200 = {
  data: DeleteRoleResponse
  status: 200
}

export type deleteRoleHandlerResponse404 = {
  data: void
  status: 404
}

export type deleteRoleHandlerResponse409 = {
  data: void
  status: 409
}

export type deleteRoleHandlerResponse500 = {
  data: void
  status: 500
}

export type deleteRoleHandlerResponseSuccess = (deleteRoleHandlerResponse200) & {
  headers: Headers;
};
export type deleteRoleHandlerResponseError = (deleteRoleHandlerResponse404 | deleteRoleHandlerResponse409 | deleteRoleHandlerResponse500) & {
  headers: Headers;
};

export type deleteRoleHandlerResponse = (deleteRoleHandlerResponseSuccess | deleteRoleHandlerResponseError)

export const getDeleteRoleHandlerUrl = (roleId: RoleId,) => {



  return `http://localhost:8080/api/v1/rbac/roles/${roleId}`
}

export const deleteRoleHandler = async (roleId: RoleId, options?: RequestInit): Promise<deleteRoleHandlerResponse> => {

  const res = await fetch(getDeleteRoleHandlerUrl(roleId),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteRoleHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRoleHandlerResponse
}



export const getDeleteRoleHandlerMutationFetcher = (roleId: RoleId, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteRoleHandler(roleId, options);
  }
}
export const getDeleteRoleHandlerMutationKey = (roleId: RoleId,) => [`http://localhost:8080/api/v1/rbac/roles/${roleId}`] as const;

export type DeleteRoleHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoleHandler>>>

export const useDeleteRoleHandler = <TError = Promise<void>>(
  roleId: RoleId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteRoleHandler>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteRoleHandler>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteRoleHandlerMutationKey(roleId);
  const swrFn = getDeleteRoleHandlerMutationFetcher(roleId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
