/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  Brand,
  BrandId,
  Category,
  CategoryId,
  CreateBrandRequest,
  CreateCategoryRequest,
  CreateFileRequest,
  CreateFileResponse,
  CreateLocalityRequest,
  CreateRoleRequest,
  CreateRoleResponse,
  CreateStateRequest,
  CreateUserRequest,
  DeleteBrandResponse,
  DeleteCategoryResponse,
  DeleteFileRequestParams,
  DeleteFileResponse,
  DeleteRoleResponse,
  DisableBrandResponse,
  ErrorResponse,
  FileId,
  GetBrandByIdResponse,
  GetCategoryByIdResponse,
  GetDownloadUrlRequestParams,
  GetDownloadUrlResponse,
  ListRolesResponse,
  Locality,
  RoleId,
  State,
  StateId,
  UpdateBrandRequest,
  UpdateBrandResponse,
  UpdateCategoryRequest,
  UpdateCategoryResponse,
  UpdateRoleRequest,
  UpdateRoleResponse,
  User
} from './schemas';

export type createFileRequestResponse201 = {
  data: CreateFileResponse
  status: 201
}

export type createFileRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createFileRequestResponse500 = {
  data: void
  status: 500
}

export type createFileRequestResponseSuccess = (createFileRequestResponse201) & {
  headers: Headers;
};
export type createFileRequestResponseError = (createFileRequestResponse400 | createFileRequestResponse500) & {
  headers: Headers;
};

export type createFileRequestResponse = (createFileRequestResponseSuccess | createFileRequestResponseError)

export const getCreateFileRequestUrl = () => {




  return `http://localhost:8080/api/v1/files`
}

export const createFileRequest = async (createFileRequest: CreateFileRequest, options?: RequestInit): Promise<createFileRequestResponse> => {

  const res = await fetch(getCreateFileRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFileRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createFileRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createFileRequestResponse
}




export const getCreateFileRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateFileRequest }) => {
    return createFileRequest(arg, options);
  }
}
export const getCreateFileRequestMutationKey = () => [`http://localhost:8080/api/v1/files`] as const;

export type CreateFileRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createFileRequest>>>

export const useCreateFileRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createFileRequest>>, TError, Key, CreateFileRequest, Awaited<ReturnType<typeof createFileRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateFileRequestMutationKey();
  const swrFn = getCreateFileRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type deleteFileRequestResponse200 = {
  data: DeleteFileResponse
  status: 200
}

export type deleteFileRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteFileRequestResponse500 = {
  data: void
  status: 500
}

export type deleteFileRequestResponseSuccess = (deleteFileRequestResponse200) & {
  headers: Headers;
};
export type deleteFileRequestResponseError = (deleteFileRequestResponse404 | deleteFileRequestResponse500) & {
  headers: Headers;
};

export type deleteFileRequestResponse = (deleteFileRequestResponseSuccess | deleteFileRequestResponseError)

export const getDeleteFileRequestUrl = (id: FileId,
    params: DeleteFileRequestParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/v1/files/${id}?${stringifiedParams}` : `http://localhost:8080/api/v1/files/${id}`
}

export const deleteFileRequest = async (id: FileId,
    params: DeleteFileRequestParams, options?: RequestInit): Promise<deleteFileRequestResponse> => {

  const res = await fetch(getDeleteFileRequestUrl(id,params),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteFileRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteFileRequestResponse
}




export const getDeleteFileRequestMutationFetcher = (id: FileId,
    params: DeleteFileRequestParams, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteFileRequest(id, params, options);
  }
}
export const getDeleteFileRequestMutationKey = (id: FileId,
    params: DeleteFileRequestParams,) => [`http://localhost:8080/api/v1/files/${id}`, ...(params ? [params]: [])] as const;

export type DeleteFileRequestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFileRequest>>>

export const useDeleteFileRequest = <TError = Promise<ErrorResponse | void>>(
  id: FileId,
    params: DeleteFileRequestParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteFileRequest>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteFileRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteFileRequestMutationKey(id,params);
  const swrFn = getDeleteFileRequestMutationFetcher(id,params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getDownloadUrlRequestResponse200 = {
  data: GetDownloadUrlResponse
  status: 200
}

export type getDownloadUrlRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getDownloadUrlRequestResponse500 = {
  data: void
  status: 500
}

export type getDownloadUrlRequestResponseSuccess = (getDownloadUrlRequestResponse200) & {
  headers: Headers;
};
export type getDownloadUrlRequestResponseError = (getDownloadUrlRequestResponse404 | getDownloadUrlRequestResponse500) & {
  headers: Headers;
};

export type getDownloadUrlRequestResponse = (getDownloadUrlRequestResponseSuccess | getDownloadUrlRequestResponseError)

export const getGetDownloadUrlRequestUrl = (id: FileId,
    params?: GetDownloadUrlRequestParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/v1/files/${id}/download-url?${stringifiedParams}` : `http://localhost:8080/api/v1/files/${id}/download-url`
}

export const getDownloadUrlRequest = async (id: FileId,
    params?: GetDownloadUrlRequestParams, options?: RequestInit): Promise<getDownloadUrlRequestResponse> => {

  const res = await fetch(getGetDownloadUrlRequestUrl(id,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDownloadUrlRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDownloadUrlRequestResponse
}




export const getGetDownloadUrlRequestKey = (id: FileId,
    params?: GetDownloadUrlRequestParams,) => [`http://localhost:8080/api/v1/files/${id}/download-url`, ...(params ? [params]: [])] as const;

export type GetDownloadUrlRequestQueryResult = NonNullable<Awaited<ReturnType<typeof getDownloadUrlRequest>>>

export const useGetDownloadUrlRequest = <TError = Promise<ErrorResponse | void>>(
  id: FileId,
    params?: GetDownloadUrlRequestParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDownloadUrlRequest>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDownloadUrlRequestKey(id,params) : null);
  const swrFn = () => getDownloadUrlRequest(id,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createStateRequestResponse201 = {
  data: State
  status: 201
}

export type createStateRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createStateRequestResponse500 = {
  data: void
  status: 500
}

export type createStateRequestResponseSuccess = (createStateRequestResponse201) & {
  headers: Headers;
};
export type createStateRequestResponseError = (createStateRequestResponse400 | createStateRequestResponse500) & {
  headers: Headers;
};

export type createStateRequestResponse = (createStateRequestResponseSuccess | createStateRequestResponseError)

export const getCreateStateRequestUrl = () => {




  return `http://localhost:8080/api/v1/locations/states`
}

export const createStateRequest = async (createStateRequest: CreateStateRequest, options?: RequestInit): Promise<createStateRequestResponse> => {

  const res = await fetch(getCreateStateRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createStateRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createStateRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createStateRequestResponse
}




export const getCreateStateRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateStateRequest }) => {
    return createStateRequest(arg, options);
  }
}
export const getCreateStateRequestMutationKey = () => [`http://localhost:8080/api/v1/locations/states`] as const;

export type CreateStateRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createStateRequest>>>

export const useCreateStateRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createStateRequest>>, TError, Key, CreateStateRequest, Awaited<ReturnType<typeof createStateRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateStateRequestMutationKey();
  const swrFn = getCreateStateRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createLocalityRequestResponse201 = {
  data: Locality
  status: 201
}

export type createLocalityRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createLocalityRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createLocalityRequestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type createLocalityRequestResponse500 = {
  data: void
  status: 500
}

export type createLocalityRequestResponseSuccess = (createLocalityRequestResponse201) & {
  headers: Headers;
};
export type createLocalityRequestResponseError = (createLocalityRequestResponse400 | createLocalityRequestResponse404 | createLocalityRequestResponse409 | createLocalityRequestResponse500) & {
  headers: Headers;
};

export type createLocalityRequestResponse = (createLocalityRequestResponseSuccess | createLocalityRequestResponseError)

export const getCreateLocalityRequestUrl = (stateId: StateId,) => {




  return `http://localhost:8080/api/v1/locations/states/${stateId}/localities`
}

export const createLocalityRequest = async (stateId: StateId,
    createLocalityRequest: CreateLocalityRequest, options?: RequestInit): Promise<createLocalityRequestResponse> => {

  const res = await fetch(getCreateLocalityRequestUrl(stateId),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLocalityRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLocalityRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createLocalityRequestResponse
}




export const getCreateLocalityRequestMutationFetcher = (stateId: StateId, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateLocalityRequest }) => {
    return createLocalityRequest(stateId, arg, options);
  }
}
export const getCreateLocalityRequestMutationKey = (stateId: StateId,) => [`http://localhost:8080/api/v1/locations/states/${stateId}/localities`] as const;

export type CreateLocalityRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createLocalityRequest>>>

export const useCreateLocalityRequest = <TError = Promise<ErrorResponse | void>>(
  stateId: StateId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createLocalityRequest>>, TError, Key, CreateLocalityRequest, Awaited<ReturnType<typeof createLocalityRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateLocalityRequestMutationKey(stateId);
  const swrFn = getCreateLocalityRequestMutationFetcher(stateId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createBrandRequestResponse201 = {
  data: Brand
  status: 201
}

export type createBrandRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createBrandRequestResponse500 = {
  data: void
  status: 500
}

export type createBrandRequestResponseSuccess = (createBrandRequestResponse201) & {
  headers: Headers;
};
export type createBrandRequestResponseError = (createBrandRequestResponse400 | createBrandRequestResponse500) & {
  headers: Headers;
};

export type createBrandRequestResponse = (createBrandRequestResponseSuccess | createBrandRequestResponseError)

export const getCreateBrandRequestUrl = () => {




  return `http://localhost:8080/api/v1/products/brands`
}

export const createBrandRequest = async (createBrandRequest: CreateBrandRequest, options?: RequestInit): Promise<createBrandRequestResponse> => {

  const res = await fetch(getCreateBrandRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBrandRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createBrandRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createBrandRequestResponse
}




export const getCreateBrandRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateBrandRequest }) => {
    return createBrandRequest(arg, options);
  }
}
export const getCreateBrandRequestMutationKey = () => [`http://localhost:8080/api/v1/products/brands`] as const;

export type CreateBrandRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createBrandRequest>>>

export const useCreateBrandRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createBrandRequest>>, TError, Key, CreateBrandRequest, Awaited<ReturnType<typeof createBrandRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateBrandRequestMutationKey();
  const swrFn = getCreateBrandRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getBrandRequestResponse200 = {
  data: GetBrandByIdResponse
  status: 200
}

export type getBrandRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getBrandRequestResponse500 = {
  data: void
  status: 500
}

export type getBrandRequestResponseSuccess = (getBrandRequestResponse200) & {
  headers: Headers;
};
export type getBrandRequestResponseError = (getBrandRequestResponse404 | getBrandRequestResponse500) & {
  headers: Headers;
};

export type getBrandRequestResponse = (getBrandRequestResponseSuccess | getBrandRequestResponseError)

export const getGetBrandRequestUrl = (id: BrandId,) => {




  return `http://localhost:8080/api/v1/products/brands/${id}`
}

export const getBrandRequest = async (id: BrandId, options?: RequestInit): Promise<getBrandRequestResponse> => {

  const res = await fetch(getGetBrandRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getBrandRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBrandRequestResponse
}




export const getGetBrandRequestKey = (id: BrandId,) => [`http://localhost:8080/api/v1/products/brands/${id}`] as const;

export type GetBrandRequestQueryResult = NonNullable<Awaited<ReturnType<typeof getBrandRequest>>>

export const useGetBrandRequest = <TError = Promise<ErrorResponse | void>>(
  id: BrandId, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getBrandRequest>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetBrandRequestKey(id) : null);
  const swrFn = () => getBrandRequest(id, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type updateBrandRequestResponse200 = {
  data: UpdateBrandResponse
  status: 200
}

export type updateBrandRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateBrandRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateBrandRequestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type updateBrandRequestResponse500 = {
  data: void
  status: 500
}

export type updateBrandRequestResponseSuccess = (updateBrandRequestResponse200) & {
  headers: Headers;
};
export type updateBrandRequestResponseError = (updateBrandRequestResponse400 | updateBrandRequestResponse404 | updateBrandRequestResponse409 | updateBrandRequestResponse500) & {
  headers: Headers;
};

export type updateBrandRequestResponse = (updateBrandRequestResponseSuccess | updateBrandRequestResponseError)

export const getUpdateBrandRequestUrl = (id: BrandId,) => {




  return `http://localhost:8080/api/v1/products/brands/${id}`
}

export const updateBrandRequest = async (id: BrandId,
    updateBrandRequest: UpdateBrandRequest, options?: RequestInit): Promise<updateBrandRequestResponse> => {

  const res = await fetch(getUpdateBrandRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateBrandRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateBrandRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateBrandRequestResponse
}




export const getUpdateBrandRequestMutationFetcher = (id: BrandId, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateBrandRequest }) => {
    return updateBrandRequest(id, arg, options);
  }
}
export const getUpdateBrandRequestMutationKey = (id: BrandId,) => [`http://localhost:8080/api/v1/products/brands/${id}`] as const;

export type UpdateBrandRequestMutationResult = NonNullable<Awaited<ReturnType<typeof updateBrandRequest>>>

export const useUpdateBrandRequest = <TError = Promise<ErrorResponse | void>>(
  id: BrandId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateBrandRequest>>, TError, Key, UpdateBrandRequest, Awaited<ReturnType<typeof updateBrandRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateBrandRequestMutationKey(id);
  const swrFn = getUpdateBrandRequestMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type deleteBrandRequestResponse200 = {
  data: DeleteBrandResponse
  status: 200
}

export type deleteBrandRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteBrandRequestResponse500 = {
  data: void
  status: 500
}

export type deleteBrandRequestResponseSuccess = (deleteBrandRequestResponse200) & {
  headers: Headers;
};
export type deleteBrandRequestResponseError = (deleteBrandRequestResponse404 | deleteBrandRequestResponse500) & {
  headers: Headers;
};

export type deleteBrandRequestResponse = (deleteBrandRequestResponseSuccess | deleteBrandRequestResponseError)

export const getDeleteBrandRequestUrl = (id: BrandId,) => {




  return `http://localhost:8080/api/v1/products/brands/${id}`
}

export const deleteBrandRequest = async (id: BrandId, options?: RequestInit): Promise<deleteBrandRequestResponse> => {

  const res = await fetch(getDeleteBrandRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteBrandRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteBrandRequestResponse
}




export const getDeleteBrandRequestMutationFetcher = (id: BrandId, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteBrandRequest(id, options);
  }
}
export const getDeleteBrandRequestMutationKey = (id: BrandId,) => [`http://localhost:8080/api/v1/products/brands/${id}`] as const;

export type DeleteBrandRequestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBrandRequest>>>

export const useDeleteBrandRequest = <TError = Promise<ErrorResponse | void>>(
  id: BrandId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteBrandRequest>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteBrandRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteBrandRequestMutationKey(id);
  const swrFn = getDeleteBrandRequestMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type disableBrandRequestResponse200 = {
  data: DisableBrandResponse
  status: 200
}

export type disableBrandRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type disableBrandRequestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type disableBrandRequestResponse500 = {
  data: void
  status: 500
}

export type disableBrandRequestResponseSuccess = (disableBrandRequestResponse200) & {
  headers: Headers;
};
export type disableBrandRequestResponseError = (disableBrandRequestResponse404 | disableBrandRequestResponse409 | disableBrandRequestResponse500) & {
  headers: Headers;
};

export type disableBrandRequestResponse = (disableBrandRequestResponseSuccess | disableBrandRequestResponseError)

export const getDisableBrandRequestUrl = (id: BrandId,) => {




  return `http://localhost:8080/api/v1/products/brands/${id}/disable`
}

export const disableBrandRequest = async (id: BrandId, options?: RequestInit): Promise<disableBrandRequestResponse> => {

  const res = await fetch(getDisableBrandRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'PATCH'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: disableBrandRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as disableBrandRequestResponse
}




export const getDisableBrandRequestMutationFetcher = (id: BrandId, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return disableBrandRequest(id, options);
  }
}
export const getDisableBrandRequestMutationKey = (id: BrandId,) => [`http://localhost:8080/api/v1/products/brands/${id}/disable`] as const;

export type DisableBrandRequestMutationResult = NonNullable<Awaited<ReturnType<typeof disableBrandRequest>>>

export const useDisableBrandRequest = <TError = Promise<ErrorResponse | void>>(
  id: BrandId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof disableBrandRequest>>, TError, Key, Arguments, Awaited<ReturnType<typeof disableBrandRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDisableBrandRequestMutationKey(id);
  const swrFn = getDisableBrandRequestMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createCategoryRequestResponse201 = {
  data: Category
  status: 201
}

export type createCategoryRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createCategoryRequestResponse500 = {
  data: void
  status: 500
}

export type createCategoryRequestResponseSuccess = (createCategoryRequestResponse201) & {
  headers: Headers;
};
export type createCategoryRequestResponseError = (createCategoryRequestResponse400 | createCategoryRequestResponse500) & {
  headers: Headers;
};

export type createCategoryRequestResponse = (createCategoryRequestResponseSuccess | createCategoryRequestResponseError)

export const getCreateCategoryRequestUrl = () => {




  return `http://localhost:8080/api/v1/products/categories`
}

export const createCategoryRequest = async (createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<createCategoryRequestResponse> => {

  const res = await fetch(getCreateCategoryRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCategoryRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createCategoryRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCategoryRequestResponse
}




export const getCreateCategoryRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateCategoryRequest }) => {
    return createCategoryRequest(arg, options);
  }
}
export const getCreateCategoryRequestMutationKey = () => [`http://localhost:8080/api/v1/products/categories`] as const;

export type CreateCategoryRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createCategoryRequest>>>

export const useCreateCategoryRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createCategoryRequest>>, TError, Key, CreateCategoryRequest, Awaited<ReturnType<typeof createCategoryRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateCategoryRequestMutationKey();
  const swrFn = getCreateCategoryRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getCategoryRequestResponse200 = {
  data: GetCategoryByIdResponse
  status: 200
}

export type getCategoryRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCategoryRequestResponse500 = {
  data: void
  status: 500
}

export type getCategoryRequestResponseSuccess = (getCategoryRequestResponse200) & {
  headers: Headers;
};
export type getCategoryRequestResponseError = (getCategoryRequestResponse404 | getCategoryRequestResponse500) & {
  headers: Headers;
};

export type getCategoryRequestResponse = (getCategoryRequestResponseSuccess | getCategoryRequestResponseError)

export const getGetCategoryRequestUrl = (id: CategoryId,) => {




  return `http://localhost:8080/api/v1/products/categories/${id}`
}

export const getCategoryRequest = async (id: CategoryId, options?: RequestInit): Promise<getCategoryRequestResponse> => {

  const res = await fetch(getGetCategoryRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCategoryRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCategoryRequestResponse
}




export const getGetCategoryRequestKey = (id: CategoryId,) => [`http://localhost:8080/api/v1/products/categories/${id}`] as const;

export type GetCategoryRequestQueryResult = NonNullable<Awaited<ReturnType<typeof getCategoryRequest>>>

export const useGetCategoryRequest = <TError = Promise<ErrorResponse | void>>(
  id: CategoryId, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCategoryRequest>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCategoryRequestKey(id) : null);
  const swrFn = () => getCategoryRequest(id, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type updateCategoryRequestResponse200 = {
  data: UpdateCategoryResponse
  status: 200
}

export type updateCategoryRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateCategoryRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateCategoryRequestResponse500 = {
  data: void
  status: 500
}

export type updateCategoryRequestResponseSuccess = (updateCategoryRequestResponse200) & {
  headers: Headers;
};
export type updateCategoryRequestResponseError = (updateCategoryRequestResponse400 | updateCategoryRequestResponse404 | updateCategoryRequestResponse500) & {
  headers: Headers;
};

export type updateCategoryRequestResponse = (updateCategoryRequestResponseSuccess | updateCategoryRequestResponseError)

export const getUpdateCategoryRequestUrl = (id: CategoryId,) => {




  return `http://localhost:8080/api/v1/products/categories/${id}`
}

export const updateCategoryRequest = async (id: CategoryId,
    updateCategoryRequest: UpdateCategoryRequest, options?: RequestInit): Promise<updateCategoryRequestResponse> => {

  const res = await fetch(getUpdateCategoryRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCategoryRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateCategoryRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCategoryRequestResponse
}




export const getUpdateCategoryRequestMutationFetcher = (id: CategoryId, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateCategoryRequest }) => {
    return updateCategoryRequest(id, arg, options);
  }
}
export const getUpdateCategoryRequestMutationKey = (id: CategoryId,) => [`http://localhost:8080/api/v1/products/categories/${id}`] as const;

export type UpdateCategoryRequestMutationResult = NonNullable<Awaited<ReturnType<typeof updateCategoryRequest>>>

export const useUpdateCategoryRequest = <TError = Promise<ErrorResponse | void>>(
  id: CategoryId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateCategoryRequest>>, TError, Key, UpdateCategoryRequest, Awaited<ReturnType<typeof updateCategoryRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateCategoryRequestMutationKey(id);
  const swrFn = getUpdateCategoryRequestMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type deleteCategoryRequestResponse200 = {
  data: DeleteCategoryResponse
  status: 200
}

export type deleteCategoryRequestResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteCategoryRequestResponse500 = {
  data: void
  status: 500
}

export type deleteCategoryRequestResponseSuccess = (deleteCategoryRequestResponse200) & {
  headers: Headers;
};
export type deleteCategoryRequestResponseError = (deleteCategoryRequestResponse404 | deleteCategoryRequestResponse500) & {
  headers: Headers;
};

export type deleteCategoryRequestResponse = (deleteCategoryRequestResponseSuccess | deleteCategoryRequestResponseError)

export const getDeleteCategoryRequestUrl = (id: CategoryId,) => {




  return `http://localhost:8080/api/v1/products/categories/${id}`
}

export const deleteCategoryRequest = async (id: CategoryId, options?: RequestInit): Promise<deleteCategoryRequestResponse> => {

  const res = await fetch(getDeleteCategoryRequestUrl(id),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteCategoryRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCategoryRequestResponse
}




export const getDeleteCategoryRequestMutationFetcher = (id: CategoryId, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteCategoryRequest(id, options);
  }
}
export const getDeleteCategoryRequestMutationKey = (id: CategoryId,) => [`http://localhost:8080/api/v1/products/categories/${id}`] as const;

export type DeleteCategoryRequestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCategoryRequest>>>

export const useDeleteCategoryRequest = <TError = Promise<ErrorResponse | void>>(
  id: CategoryId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteCategoryRequest>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteCategoryRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteCategoryRequestMutationKey(id);
  const swrFn = getDeleteCategoryRequestMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type listRolesHandlerResponse200 = {
  data: ListRolesResponse
  status: 200
}

export type listRolesHandlerResponse500 = {
  data: void
  status: 500
}

export type listRolesHandlerResponseSuccess = (listRolesHandlerResponse200) & {
  headers: Headers;
};
export type listRolesHandlerResponseError = (listRolesHandlerResponse500) & {
  headers: Headers;
};

export type listRolesHandlerResponse = (listRolesHandlerResponseSuccess | listRolesHandlerResponseError)

export const getListRolesHandlerUrl = () => {




  return `http://localhost:8080/api/v1/rbac/roles`
}

export const listRolesHandler = async ( options?: RequestInit): Promise<listRolesHandlerResponse> => {

  const res = await fetch(getListRolesHandlerUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listRolesHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listRolesHandlerResponse
}




export const getListRolesHandlerKey = () => [`http://localhost:8080/api/v1/rbac/roles`] as const;

export type ListRolesHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof listRolesHandler>>>

export const useListRolesHandler = <TError = Promise<void>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listRolesHandler>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListRolesHandlerKey() : null);
  const swrFn = () => listRolesHandler(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createRoleHandlerResponse201 = {
  data: CreateRoleResponse
  status: 201
}

export type createRoleHandlerResponse422 = {
  data: void
  status: 422
}

export type createRoleHandlerResponse500 = {
  data: void
  status: 500
}

export type createRoleHandlerResponseSuccess = (createRoleHandlerResponse201) & {
  headers: Headers;
};
export type createRoleHandlerResponseError = (createRoleHandlerResponse422 | createRoleHandlerResponse500) & {
  headers: Headers;
};

export type createRoleHandlerResponse = (createRoleHandlerResponseSuccess | createRoleHandlerResponseError)

export const getCreateRoleHandlerUrl = () => {




  return `http://localhost:8080/api/v1/rbac/roles`
}

export const createRoleHandler = async (createRoleRequest: CreateRoleRequest, options?: RequestInit): Promise<createRoleHandlerResponse> => {

  const res = await fetch(getCreateRoleHandlerUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRoleHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRoleHandlerResponse
}




export const getCreateRoleHandlerMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateRoleRequest }) => {
    return createRoleHandler(arg, options);
  }
}
export const getCreateRoleHandlerMutationKey = () => [`http://localhost:8080/api/v1/rbac/roles`] as const;

export type CreateRoleHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof createRoleHandler>>>

export const useCreateRoleHandler = <TError = Promise<void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createRoleHandler>>, TError, Key, CreateRoleRequest, Awaited<ReturnType<typeof createRoleHandler>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRoleHandlerMutationKey();
  const swrFn = getCreateRoleHandlerMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type updateRoleHandlerResponse200 = {
  data: UpdateRoleResponse
  status: 200
}

export type updateRoleHandlerResponse404 = {
  data: void
  status: 404
}

export type updateRoleHandlerResponse422 = {
  data: void
  status: 422
}

export type updateRoleHandlerResponse500 = {
  data: void
  status: 500
}

export type updateRoleHandlerResponseSuccess = (updateRoleHandlerResponse200) & {
  headers: Headers;
};
export type updateRoleHandlerResponseError = (updateRoleHandlerResponse404 | updateRoleHandlerResponse422 | updateRoleHandlerResponse500) & {
  headers: Headers;
};

export type updateRoleHandlerResponse = (updateRoleHandlerResponseSuccess | updateRoleHandlerResponseError)

export const getUpdateRoleHandlerUrl = (roleId: RoleId,) => {




  return `http://localhost:8080/api/v1/rbac/roles/${roleId}`
}

export const updateRoleHandler = async (roleId: RoleId,
    updateRoleRequest: UpdateRoleRequest, options?: RequestInit): Promise<updateRoleHandlerResponse> => {

  const res = await fetch(getUpdateRoleHandlerUrl(roleId),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateRoleHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateRoleHandlerResponse
}




export const getUpdateRoleHandlerMutationFetcher = (roleId: RoleId, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateRoleRequest }) => {
    return updateRoleHandler(roleId, arg, options);
  }
}
export const getUpdateRoleHandlerMutationKey = (roleId: RoleId,) => [`http://localhost:8080/api/v1/rbac/roles/${roleId}`] as const;

export type UpdateRoleHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoleHandler>>>

export const useUpdateRoleHandler = <TError = Promise<void>>(
  roleId: RoleId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateRoleHandler>>, TError, Key, UpdateRoleRequest, Awaited<ReturnType<typeof updateRoleHandler>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateRoleHandlerMutationKey(roleId);
  const swrFn = getUpdateRoleHandlerMutationFetcher(roleId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type deleteRoleHandlerResponse200 = {
  data: DeleteRoleResponse
  status: 200
}

export type deleteRoleHandlerResponse404 = {
  data: void
  status: 404
}

export type deleteRoleHandlerResponse409 = {
  data: void
  status: 409
}

export type deleteRoleHandlerResponse500 = {
  data: void
  status: 500
}

export type deleteRoleHandlerResponseSuccess = (deleteRoleHandlerResponse200) & {
  headers: Headers;
};
export type deleteRoleHandlerResponseError = (deleteRoleHandlerResponse404 | deleteRoleHandlerResponse409 | deleteRoleHandlerResponse500) & {
  headers: Headers;
};

export type deleteRoleHandlerResponse = (deleteRoleHandlerResponseSuccess | deleteRoleHandlerResponseError)

export const getDeleteRoleHandlerUrl = (roleId: RoleId,) => {




  return `http://localhost:8080/api/v1/rbac/roles/${roleId}`
}

export const deleteRoleHandler = async (roleId: RoleId, options?: RequestInit): Promise<deleteRoleHandlerResponse> => {

  const res = await fetch(getDeleteRoleHandlerUrl(roleId),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteRoleHandlerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRoleHandlerResponse
}




export const getDeleteRoleHandlerMutationFetcher = (roleId: RoleId, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteRoleHandler(roleId, options);
  }
}
export const getDeleteRoleHandlerMutationKey = (roleId: RoleId,) => [`http://localhost:8080/api/v1/rbac/roles/${roleId}`] as const;

export type DeleteRoleHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoleHandler>>>

export const useDeleteRoleHandler = <TError = Promise<void>>(
  roleId: RoleId, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteRoleHandler>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteRoleHandler>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteRoleHandlerMutationKey(roleId);
  const swrFn = getDeleteRoleHandlerMutationFetcher(roleId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type createUserRequestResponse201 = {
  data: User
  status: 201
}

export type createUserRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createUserRequestResponse500 = {
  data: void
  status: 500
}

export type createUserRequestResponseSuccess = (createUserRequestResponse201) & {
  headers: Headers;
};
export type createUserRequestResponseError = (createUserRequestResponse400 | createUserRequestResponse500) & {
  headers: Headers;
};

export type createUserRequestResponse = (createUserRequestResponseSuccess | createUserRequestResponseError)

export const getCreateUserRequestUrl = () => {




  return `http://localhost:8080/api/v1/user`
}

export const createUserRequest = async (createUserRequest: CreateUserRequest, options?: RequestInit): Promise<createUserRequestResponse> => {

  const res = await fetch(getCreateUserRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createUserRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserRequestResponse
}




export const getCreateUserRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateUserRequest }) => {
    return createUserRequest(arg, options);
  }
}
export const getCreateUserRequestMutationKey = () => [`http://localhost:8080/api/v1/user`] as const;

export type CreateUserRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createUserRequest>>>

export const useCreateUserRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createUserRequest>>, TError, Key, CreateUserRequest, Awaited<ReturnType<typeof createUserRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateUserRequestMutationKey();
  const swrFn = getCreateUserRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
