/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  Category,
  CreateCategoryRequest,
  ErrorResponse
} from './schemas';

export type createCategoryRequestResponse201 = {
  data: Category
  status: 201
}

export type createCategoryRequestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createCategoryRequestResponse500 = {
  data: void
  status: 500
}

export type createCategoryRequestResponseSuccess = (createCategoryRequestResponse201) & {
  headers: Headers;
};
export type createCategoryRequestResponseError = (createCategoryRequestResponse400 | createCategoryRequestResponse500) & {
  headers: Headers;
};

export type createCategoryRequestResponse = (createCategoryRequestResponseSuccess | createCategoryRequestResponseError)

export const getCreateCategoryRequestUrl = () => {




  return `http://localhost:8080/api/v1/products/categories`
}

export const createCategoryRequest = async (createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<createCategoryRequestResponse> => {

  const res = await fetch(getCreateCategoryRequestUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCategoryRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createCategoryRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCategoryRequestResponse
}




export const getCreateCategoryRequestMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateCategoryRequest }) => {
    return createCategoryRequest(arg, options);
  }
}
export const getCreateCategoryRequestMutationKey = () => [`http://localhost:8080/api/v1/products/categories`] as const;

export type CreateCategoryRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createCategoryRequest>>>

export const useCreateCategoryRequest = <TError = Promise<ErrorResponse | void>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createCategoryRequest>>, TError, Key, CreateCategoryRequest, Awaited<ReturnType<typeof createCategoryRequest>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateCategoryRequestMutationKey();
  const swrFn = getCreateCategoryRequestMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
