/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * ciclo
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

export const CreateCategoryRequestBody = zod.object({
  "description": zod.string().nullish(),
  "display_name": zod.string(),
  "parent_id": zod.union([zod.null(), zod.uuid()]).optional(),
  "slug": zod.string()
})

export const CreateCategoryRequestResponse = zod.object({
  "created_at": zod.iso.datetime({ "offset": true }),
  "description": zod.string().nullish(),
  "display_name": zod.string(),
  "id": zod.uuid(),
  "parent_id": zod.union([zod.null(), zod.uuid()]).optional(),
  "slug": zod.string()
})

export const CreateBrandRequestBody = zod.object({
  "display_name": zod.string(),
  "image_url": zod.string().nullish(),
})

export const CreateBrandRequestResponse = zod.object({
  "created_at": zod.iso.datetime({ "offset": true }),
  "display_name": zod.string(),
  "image_url": zod.string().nullish(),
  "id": zod.uuid(),
})
