rules:
  description-empty: # Description shouldn't be empty
    level: error
  subject-empty: # Subject line should exist
    level: error
  type-empty: # Type must not be empty
    level: error
  type:
    level: error
    options:
      - feat
      - fix
      - ci
      - docs
      - chore
      - test
      - merge
  scope-format:
    level: error
    format: ^[a-z0-9]*$
