/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutCustomerRouteImport } from './routes/_layout/customer'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutInventoryRouteImport } from './routes/_layout/inventory'
import { Route as LayoutLocationsRouteImport } from './routes/_layout/locations'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutSalesRouteImport } from './routes/_layout/sales'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutWarehousesRouteImport } from './routes/_layout/warehouses'
import { Route as LayoutBrandsIndexRouteImport } from './routes/_layout/brands/index'
import { Route as LayoutCategoriesIndexRouteImport } from './routes/_layout/categories/index'
import { Route as LayoutCategoriesCategoryIdRouteImport } from './routes/_layout/categories/$categoryId'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout/products/index'
import { Route as LayoutProductsProductIdRouteImport } from './routes/_layout/products/$productId'
import { Route as LayoutTeamIndexRouteImport } from './routes/_layout/team.index'
import { Route as LayoutTeamPermisosRouteImport } from './routes/_layout/team.permisos'
import { Route as LayoutTeamRolesRouteImport } from './routes/_layout/team.roles'
import { Route as LayoutWarehousesIndexRouteImport } from './routes/_layout/warehouses/index'
import { Route as LayoutWarehousesWarehouseIdRouteImport } from './routes/_layout/warehouses/$warehouseId'
import { Route as LayoutCategoriesCategoryIdEditRouteImport } from './routes/_layout/categories/$categoryId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutCustomerRoute = LayoutCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryRoute = LayoutInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocationsRoute = LayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesRoute = LayoutSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehousesRoute = LayoutWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrandsIndexRoute = LayoutBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesIndexRoute = LayoutCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesCategoryIdRoute =
  LayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsProductIdRoute = LayoutProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamIndexRoute = LayoutTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTeamRoute,
} as any)
const LayoutTeamPermisosRoute = LayoutTeamPermisosRouteImport.update({
  id: '/permisos',
  path: '/permisos',
  getParentRoute: () => LayoutTeamRoute,
} as any)
const LayoutTeamRolesRoute = LayoutTeamRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LayoutTeamRoute,
} as any)
const LayoutWarehousesIndexRoute = LayoutWarehousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutWarehousesRoute,
} as any)
const LayoutWarehousesWarehouseIdRoute =
  LayoutWarehousesWarehouseIdRouteImport.update({
    id: '/$warehouseId',
    path: '/$warehouseId',
    getParentRoute: () => LayoutWarehousesRoute,
  } as any)
const LayoutCategoriesCategoryIdEditRoute =
  LayoutCategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId_/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customer': typeof LayoutCustomerRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inventory': typeof LayoutInventoryRoute
  '/locations': typeof LayoutLocationsRoute
  '/profile': typeof LayoutProfileRoute
  '/sales': typeof LayoutSalesRoute
  '/team': typeof LayoutTeamRouteWithChildren
  '/warehouses': typeof LayoutWarehousesRouteWithChildren
  '/categories/$categoryId': typeof LayoutCategoriesCategoryIdRoute
  '/products/$productId': typeof LayoutProductsProductIdRoute
  '/team/permisos': typeof LayoutTeamPermisosRoute
  '/team/roles': typeof LayoutTeamRolesRoute
  '/warehouses/$warehouseId': typeof LayoutWarehousesWarehouseIdRoute
  '/brands/': typeof LayoutBrandsIndexRoute
  '/categories/': typeof LayoutCategoriesIndexRoute
  '/products/': typeof LayoutProductsIndexRoute
  '/team/': typeof LayoutTeamIndexRoute
  '/warehouses/': typeof LayoutWarehousesIndexRoute
  '/categories/$categoryId/edit': typeof LayoutCategoriesCategoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customer': typeof LayoutCustomerRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inventory': typeof LayoutInventoryRoute
  '/locations': typeof LayoutLocationsRoute
  '/profile': typeof LayoutProfileRoute
  '/sales': typeof LayoutSalesRoute
  '/categories/$categoryId': typeof LayoutCategoriesCategoryIdRoute
  '/products/$productId': typeof LayoutProductsProductIdRoute
  '/team/permisos': typeof LayoutTeamPermisosRoute
  '/team/roles': typeof LayoutTeamRolesRoute
  '/warehouses/$warehouseId': typeof LayoutWarehousesWarehouseIdRoute
  '/brands': typeof LayoutBrandsIndexRoute
  '/categories': typeof LayoutCategoriesIndexRoute
  '/products': typeof LayoutProductsIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/warehouses': typeof LayoutWarehousesIndexRoute
  '/categories/$categoryId/edit': typeof LayoutCategoriesCategoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/customer': typeof LayoutCustomerRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/inventory': typeof LayoutInventoryRoute
  '/_layout/locations': typeof LayoutLocationsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/sales': typeof LayoutSalesRoute
  '/_layout/team': typeof LayoutTeamRouteWithChildren
  '/_layout/warehouses': typeof LayoutWarehousesRouteWithChildren
  '/_layout/categories/$categoryId': typeof LayoutCategoriesCategoryIdRoute
  '/_layout/products/$productId': typeof LayoutProductsProductIdRoute
  '/_layout/team/permisos': typeof LayoutTeamPermisosRoute
  '/_layout/team/roles': typeof LayoutTeamRolesRoute
  '/_layout/warehouses/$warehouseId': typeof LayoutWarehousesWarehouseIdRoute
  '/_layout/brands/': typeof LayoutBrandsIndexRoute
  '/_layout/categories/': typeof LayoutCategoriesIndexRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
  '/_layout/team/': typeof LayoutTeamIndexRoute
  '/_layout/warehouses/': typeof LayoutWarehousesIndexRoute
  '/_layout/categories/$categoryId_/edit': typeof LayoutCategoriesCategoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customer'
    | '/dashboard'
    | '/inventory'
    | '/locations'
    | '/profile'
    | '/sales'
    | '/team'
    | '/warehouses'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/team/permisos'
    | '/team/roles'
    | '/warehouses/$warehouseId'
    | '/brands/'
    | '/categories/'
    | '/products/'
    | '/team/'
    | '/warehouses/'
    | '/categories/$categoryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customer'
    | '/dashboard'
    | '/inventory'
    | '/locations'
    | '/profile'
    | '/sales'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/team/permisos'
    | '/team/roles'
    | '/warehouses/$warehouseId'
    | '/brands'
    | '/categories'
    | '/products'
    | '/team'
    | '/warehouses'
    | '/categories/$categoryId/edit'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/customer'
    | '/_layout/dashboard'
    | '/_layout/inventory'
    | '/_layout/locations'
    | '/_layout/profile'
    | '/_layout/sales'
    | '/_layout/team'
    | '/_layout/warehouses'
    | '/_layout/categories/$categoryId'
    | '/_layout/products/$productId'
    | '/_layout/team/permisos'
    | '/_layout/team/roles'
    | '/_layout/warehouses/$warehouseId'
    | '/_layout/brands/'
    | '/_layout/categories/'
    | '/_layout/products/'
    | '/_layout/team/'
    | '/_layout/warehouses/'
    | '/_layout/categories/$categoryId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/customer': {
      id: '/_layout/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof LayoutCustomerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory': {
      id: '/_layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof LayoutInventoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/locations': {
      id: '/_layout/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LayoutLocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales': {
      id: '/_layout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouses': {
      id: '/_layout/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof LayoutWarehousesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brands/': {
      id: '/_layout/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof LayoutBrandsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories/': {
      id: '/_layout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof LayoutCategoriesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories/$categoryId': {
      id: '/_layout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof LayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/$productId': {
      id: '/_layout/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof LayoutProductsProductIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team/': {
      id: '/_layout/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof LayoutTeamIndexRouteImport
      parentRoute: typeof LayoutTeamRoute
    }
    '/_layout/team/permisos': {
      id: '/_layout/team/permisos'
      path: '/permisos'
      fullPath: '/team/permisos'
      preLoaderRoute: typeof LayoutTeamPermisosRouteImport
      parentRoute: typeof LayoutTeamRoute
    }
    '/_layout/team/roles': {
      id: '/_layout/team/roles'
      path: '/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof LayoutTeamRolesRouteImport
      parentRoute: typeof LayoutTeamRoute
    }
    '/_layout/warehouses/': {
      id: '/_layout/warehouses/'
      path: '/'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof LayoutWarehousesIndexRouteImport
      parentRoute: typeof LayoutWarehousesRoute
    }
    '/_layout/warehouses/$warehouseId': {
      id: '/_layout/warehouses/$warehouseId'
      path: '/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof LayoutWarehousesWarehouseIdRouteImport
      parentRoute: typeof LayoutWarehousesRoute
    }
    '/_layout/categories/$categoryId_/edit': {
      id: '/_layout/categories/$categoryId_/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof LayoutCategoriesCategoryIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutTeamRouteChildren {
  LayoutTeamPermisosRoute: typeof LayoutTeamPermisosRoute
  LayoutTeamRolesRoute: typeof LayoutTeamRolesRoute
  LayoutTeamIndexRoute: typeof LayoutTeamIndexRoute
}

const LayoutTeamRouteChildren: LayoutTeamRouteChildren = {
  LayoutTeamPermisosRoute: LayoutTeamPermisosRoute,
  LayoutTeamRolesRoute: LayoutTeamRolesRoute,
  LayoutTeamIndexRoute: LayoutTeamIndexRoute,
}

const LayoutTeamRouteWithChildren = LayoutTeamRoute._addFileChildren(
  LayoutTeamRouteChildren,
)

interface LayoutWarehousesRouteChildren {
  LayoutWarehousesWarehouseIdRoute: typeof LayoutWarehousesWarehouseIdRoute
  LayoutWarehousesIndexRoute: typeof LayoutWarehousesIndexRoute
}

const LayoutWarehousesRouteChildren: LayoutWarehousesRouteChildren = {
  LayoutWarehousesWarehouseIdRoute: LayoutWarehousesWarehouseIdRoute,
  LayoutWarehousesIndexRoute: LayoutWarehousesIndexRoute,
}

const LayoutWarehousesRouteWithChildren =
  LayoutWarehousesRoute._addFileChildren(LayoutWarehousesRouteChildren)

interface LayoutRouteChildren {
  LayoutCustomerRoute: typeof LayoutCustomerRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutInventoryRoute: typeof LayoutInventoryRoute
  LayoutLocationsRoute: typeof LayoutLocationsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSalesRoute: typeof LayoutSalesRoute
  LayoutTeamRoute: typeof LayoutTeamRouteWithChildren
  LayoutWarehousesRoute: typeof LayoutWarehousesRouteWithChildren
  LayoutCategoriesCategoryIdRoute: typeof LayoutCategoriesCategoryIdRoute
  LayoutProductsProductIdRoute: typeof LayoutProductsProductIdRoute
  LayoutBrandsIndexRoute: typeof LayoutBrandsIndexRoute
  LayoutCategoriesIndexRoute: typeof LayoutCategoriesIndexRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
  LayoutCategoriesCategoryIdEditRoute: typeof LayoutCategoriesCategoryIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCustomerRoute: LayoutCustomerRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutInventoryRoute: LayoutInventoryRoute,
  LayoutLocationsRoute: LayoutLocationsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSalesRoute: LayoutSalesRoute,
  LayoutTeamRoute: LayoutTeamRouteWithChildren,
  LayoutWarehousesRoute: LayoutWarehousesRouteWithChildren,
  LayoutCategoriesCategoryIdRoute: LayoutCategoriesCategoryIdRoute,
  LayoutProductsProductIdRoute: LayoutProductsProductIdRoute,
  LayoutBrandsIndexRoute: LayoutBrandsIndexRoute,
  LayoutCategoriesIndexRoute: LayoutCategoriesIndexRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
  LayoutCategoriesCategoryIdEditRoute: LayoutCategoriesCategoryIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
