/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutSalesRouteImport } from './routes/_layout/sales'
import { Route as LayoutLocationsRouteImport } from './routes/_layout/locations'
import { Route as LayoutInventoryRouteImport } from './routes/_layout/inventory'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesRoute = LayoutSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocationsRoute = LayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryRoute = LayoutInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inventory': typeof LayoutInventoryRoute
  '/locations': typeof LayoutLocationsRoute
  '/sales': typeof LayoutSalesRoute
  '/team': typeof LayoutTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inventory': typeof LayoutInventoryRoute
  '/locations': typeof LayoutLocationsRoute
  '/sales': typeof LayoutSalesRoute
  '/team': typeof LayoutTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/inventory': typeof LayoutInventoryRoute
  '/_layout/locations': typeof LayoutLocationsRoute
  '/_layout/sales': typeof LayoutSalesRoute
  '/_layout/team': typeof LayoutTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/inventory'
    | '/locations'
    | '/sales'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/inventory'
    | '/locations'
    | '/sales'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/_layout/inventory'
    | '/_layout/locations'
    | '/_layout/sales'
    | '/_layout/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales': {
      id: '/_layout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/locations': {
      id: '/_layout/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LayoutLocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory': {
      id: '/_layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof LayoutInventoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutInventoryRoute: typeof LayoutInventoryRoute
  LayoutLocationsRoute: typeof LayoutLocationsRoute
  LayoutSalesRoute: typeof LayoutSalesRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutInventoryRoute: LayoutInventoryRoute,
  LayoutLocationsRoute: LayoutLocationsRoute,
  LayoutSalesRoute: LayoutSalesRoute,
  LayoutTeamRoute: LayoutTeamRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
